# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='date_upload',
        ),
    ]
