# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20190203_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
