# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20190203_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='photopost',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.RelatedPhoto'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='photoInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.PhotoInfo'),
        ),
    ]
