# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_auto_20190207_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
