# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_auto_20190208_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='uploads/', verbose_name='Imagen'),
        ),
    ]
